### ISSUE TITLE
Key retrieval from external sources

### ISSUE THREAD

**Issue by justinteaw** [rabbitmq/rabbitmq-auth-backend-uaa#13]
Currently, the keys are hard-coded in the configuration file.  It would be better if it can retrieve it from a well known endpoint as specified by oAuth 2.0 specs and cache it.  Also it would be good if there's a delay flag which when is true, only goes to the endpoint when there is a message to process.

**Comment by michaelklishin** [comment]
Let's stick to one feature per issue. RabbitMQ auth backends are called at specific moments
and this plugin is not going to change that. There is a generic auth backend cache plugin that greatly reduces the number of requests to backend services.

Certificate management is a complicated problem, as our trust store plugin experience suggests. Using CredHub is our most likely course of action. Local filesystem and external sources are considered to be less secure by some.
