### ISSUE TITLE
Change how scopes are translated into resource records/permissions

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-uaa#2]
Currently we use a convention that mashes together vhosts, resource kinds, permissions plus it hardcodes access to specific resources (doesn't support wildcards).

Since OAuth 2.0 scopes are arbitrary strings, a more flexible approach would be to switch to convention-based scope names:

 * `vhost:{value}` to indicate access to vhosts (in hosted RabbitMQ scenarios often there will be only one per user account)
 * `configure:{value}` (e.g. `configure:*`) for the `configure` permission
 * `read:{value}` (e.g. `read:*`) for the `read` permission
 * `write:{value}` (e.g. `write:*`) for the `write` permission
 * `tags:{comma-separated list}` for user tags

when a permission is not provided, the plugin should fall back to a configurable default.

**Comment by hairyhum** [comment]
So how could one define permissions to couple of vhosts with different resource permissions in them?

**Comment by michaelklishin** [comment]
@hairyhum that's a good question. With this scheme, there is no way to do that. I don't think we have this problem in the BOSH release, however: currently every service instance binding creates a new pair of users (one for messaging, one for management).

We can tweak the convention to accommodate your case but it would make things a lot more complicated.

**Comment by hairyhum** [comment]
Here is a relatively simple option that respects rabbitmq permissions model:

Permit read for vhosts starting with `foo`, to resource ending with `bar`: `read:foo*/*bar`

Permit configure for vhost `foo`, to resource `bar`: `configure:foo/bar`

Vhosts and resources names should be urlencoded. But this is required to use wildcards anyway.

**Comment by michaelklishin** [comment]
Was addressed a while back in #4.
