### ISSUE TITLE
Accept simple strings and space separated strings in addition to arrays for fields "aud" and "scope"

### ISSUE THREAD

**Issue by janniswarnat** [rabbitmq/rabbitmq-auth-backend-uaa#24]
Hi all,

currently the  rabbitmq-auth-backend-oauth2 expects the fields `scope` and `aud` of an access token to contain arrays because CloudFoundry UAA provides them this way. Other OpenID providers may provide simple strings or space separated strings for these fields, e.g.:

`"aud": "rabbitmq"`
`"scope": "rabbitmq.read:*/* rabbitmq.write:*/* rabbitmq.configure:*/*"`

It would be great if rabbitmq-auth-backend-oauth2 could verify values in this format also, which follows the definition in the OAuth2 standard  (https://tools.ietf.org/html/rfc6749#section-3.3). Quote:

> The value of the scope parameter is expressed as a list of space-delimited, case-sensitive strings.

Here are some notes to reproduce the issue with https://auth0.com/ (an alternative would be Keycloak 5.0.0):

- Sign up

- Create a Custom API named `rabbitmq` with Identifier (= audience) `rabbitmq` and Signing Algorithm RS256 (this should also create an Auth0 "application" automatically)

- Allow grant type `password` for application `rabbitmq` in Advanced Settings

- Add permissions to API `rabbitmq`, e.g. `rabbitmq.read:*/*`, `rabbitmq.write:*/*` and `rabbitmq.configure:*/*`

- Create a user

- Download the Postman collection from https://auth0.com/docs/api/postman

- Retrieve  an access token, e.g. by using the request "Resource Owner Password" in folder "Get Access Token". Parameters: 
grant_type: `password`
audience: `rabbitmq`
username: <username>
password: <password>
client_id:
client_secret:
scope: `rabbitmq.read:*/* rabbitmq.write:*/* rabbitmq.configure:*/*`

Try to access RabbitMQ using the resulting access token in the password field.

Please get back to me if I can provide more help in reproducing the issue.

Best regards

Jannis

**Comment by michaelklishin** [comment]
Thanks for the defaults. Handling string values for `aud` is a no-brained, it seems to be safe for `scope` as well.
