### ISSUE TITLE
plugin build

### ISSUE THREAD

**Issue by deathcoder** [rabbitmq/rabbitmq-auth-backend-uaa#25]
Hi, i want to try this plugin, can you please publish a pre-built binary working with rabbitmq 3.8?

i have found #7 and #9 but they are for older versions

**Comment by michaelklishin** [comment]
Building almost every plugin these days is a matter of having [build dependencies](https://www.rabbitmq.com/build-server.html) installed and then running

```
git clone https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2.git
cd rabbitmq-auth-backend-oauth2
gmake dist
ls -l ./plugins/
```

**Comment by michaelklishin** [comment]
[rabbitmq_auth_backend_oauth2-f48bf98.ez.zip](https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2/files/3090738/rabbitmq_auth_backend_oauth2-f48bf98.ez.zip) (an archive because GitHub does not support `.ez` files).

**Comment by deathcoder** [comment]
Thanks, didn't know there was an easy way to do it
