### ISSUE TITLE
The project license  

### ISSUE THREAD

**Issue by athena0lily** [rabbitmq/rabbitmq-auth-backend-uaa#33]
Hi,
Sorry, I didn't find any other proper channels to ask such question so just post it here.
We are very interested with this project and wonder what's the license of this project?

**Comment by acogoluegnes** [comment]
This plugin is [released under the Mozilla Public License 1.1, same as RabbitMQ](https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2#license-and-copyright).

**Comment by michaelklishin** [comment]
FTR, RabbitMQ has a [public mailing list](https://groups.google.com/forum/#!forum/rabbitmq-users).
