### ISSUE TITLE
keycloak jwt format is different with UAA token

### ISSUE THREAD

**Issue by taijitao** [rabbitmq/rabbitmq-auth-backend-uaa#36]
hi, 
I downloaded the rabbitmq-public-umbrella and compiled it with RABBIT_VSN=3.8.0.
I have two questions.
1. if i changed the rabbitmq.config like
```
[
  {rabbit, [
    {auth_backends, [rabbit_auth_backend_oauth2, rabbit_auth_backend_internal]}
  ]},
```
the auth job will be done by rabbit_auth_backend_internal instead of rabbit_auth_backend_oauth2.
In order to use rabbit_auth_backend_oauth2, i have to remove rabbit_auth_backend_internal.
so they can't work together, can they?
If only one of them could be used, it's unconvenience that GUI (like management) should use token.

2. format of JWT from keycloak is different from uaa.
lots of fields are different.
```
  "authorization": {
    "permissions": [
      {
        "scopes": [
          "rabbitmq-resource.read:*/*"
        ],
        "rsid": "2c390fe4-02ad-41c7-98a2-cebb8c60ccf1",
        "rsname": "allvhost"
      },
      {
        "scopes": [
          "rabbitmq-resource-read"
        ],
        "rsid": "e7f12e94-4c34-43d8-b2b1-c516af644cee",
        "rsname": "vhost1"
      },
      {
        "rsid": "12ac3d1c-28c2-4521-8e33-0952eff10bd9",
        "rsname": "Default Resource"
      }
    ]
  },
  "scope": "email profile",
```
The decode token likes:
```
{ok,#{<<"acr">> => <<"1">>,
      <<"aud">> => [<<"rabbitmq-resource">>],
      <<"auth_time">> => 0,
      <<"authorization">> =>
          #{<<"permissions">> =>
                [#{<<"rsid">> => <<"2c390fe4-02ad-41c7-98a2-cebb8c60ccf1">>,
                   <<"rsname">> => <<"allvhost">>,
                   <<"scopes">> => [<<"rabbitmq-resource.read:*/*">>]},
                 #{<<"rsid">> => <<"e7f12e94-4c34-43d8-b2b1-c516af644cee">>,
                   <<"rsname">> => <<"vhost1">>,
                   <<"scopes">> => [<<"rabbitmq-resource-read">>]},
                 #{<<"rsid">> => <<"12ac3d1c-28c2-4521-8e33-0952eff10bd9">>,
                   <<"rsname">> => <<"Default Resource">>}]},
      <<"azp">> => <<"rabbitmq-resource">>,
      <<"email">> => <<"tao.zou@qq.com">>,<<"email_verified">> => false,
      <<"exp">> => 1564551016,<<"family_name">> => <<"zou">>,
      <<"given_name">> => <<"tao">>,<<"iat">> => 1564550716,
      <<"iss">> => <<"https://135.251.108.55/auth/realms/rabbitmqauth">>,
      <<"jti">> => <<"0c07b4b7-469a-4ffa-ae31-7803d81f56b3">>,
      <<"name">> => <<"tao zou">>,<<"nbf">> => 0,
      <<"preferred_username">> => <<"tazou">>,
      <<"realm_access">> =>
          #{<<"roles">> =>
                [<<"offline_access">>,<<"rabbitmquser">>,
                 <<"uma_authorization">>]},
      <<"resource_access">> =>
          #{<<"account">> =>
                #{<<"roles">> =>
                      [<<"manage-account">>,<<"manage-account-links">>,
                       <<"view-profile">>]}},
      <<"scope">> => [],
      <<"session_state">> => <<"3b9b0692-6373-4c89-9b88-5b6875fd89c6">>,
      <<"sub">> => <<"a89843ac-828f-4c4d-a656-70780656cb2d">>,
      <<"typ">> => <<"Bearer">>}}
```
 backend_oauth2 extracted scopes from 'scope' as a list. so jwt from keycloak didn't work. do you have any plan to support keycloak?
or could i change the codes to meet my requirement? what's the procedure I should follow if I need to change them?

B.R,
Tao

**Comment by michaelklishin** [comment]
Thank you for your time.

Team RabbitMQ uses GitHub issues for specific actionable items engineers can work on. GitHub issues are not used for questions, investigations, root cause analysis, discussions of potential issues, etc (as defined by this team).

We get at least a dozen of questions through various venues every single day, often light on details.
At that rate GitHub issues can very quickly turn into a something impossible to navigate and make sense of even for our team. Because GitHub is a tool our team uses heavily nearly every day, the signal/noise ratio of issues is something we care about a lot.

Please post this to [rabbitmq-users](https://groups.google.com/forum/#!forum/rabbitmq-users).

Thank you.

**Comment by michaelklishin** [comment]
Please do not file GitHub issues with questions.

This plugin works like any other authN/authZ backend. It can be combined with other backends, although I'd question how much sense it makes. See the [Access Control guide](https://www.rabbitmq.com/access-control.html).

Keycloak uses a widely different token field structure from UAA. The `scopes` field is not technically in the JWT spec, so I guess that's fair. Scope extraction is [easy to modify](https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2/blob/master/src/rabbit_auth_backend_oauth2.erl#L189). I don't know if we'd get into the business of supporting many token providers but it should be easy enough to extend this plugin to support
N strategies with UAA being the default one. It's not something we had in scope (no pun intended) for 3.8.

@acogoluegnes WDYT?

**Comment by michaelklishin** [comment]
Moved to https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2/issues/37. We offer no guarantees but it looks like a small enough change to be considered for `3.8.0`. Let's see what the rest of the core team say.

**Comment by acogoluegnes** [comment]
@michaelklishin If it's just a matter of extracting the scopes in a different way, this should be straightforward indeed.
