### ISSUE TITLE
Consider supporting Keycloak token document format

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-auth-backend-uaa#37]
See #36 for background.

Currently token extraction assumes the format used by UAA. It should be reasonably straightforward to abstract the field extraction part and introduce support for [Keycloak](https://www.keycloak.org/index.html).

We specifically care about extracting the username, token's scopes, and user tags, which is just a handful of functions in `rabbit_auth_backend_oauth2`.

**Comment by michaelklishin** [comment]
@taijitao can you provide us with a Keycloak-generated JWT with a very long expiration date (say, a few years form now) and a one-off key you can share so that we can get started on this? Keycloak turned out to be a pretty non-trivial service to get going with.

**Comment by taijitao** [comment]
`eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJnRmZTRi1oSE40SHpWWDVUUHczeGQ5WHp1Nk03Sm1xbUlLWmc2UUZvbHNNIn0.eyJqdGkiOiI4ZWMwNmU3ZS00MjE1LTQwOGQtOGI3Ni1kODU3ZDVhNTg1ZWEiLCJleHAiOjE2MDc4MTk2NjEsIm5iZiI6MCwiaWF0IjoxNTY0NjE5NjYyLCJpc3MiOiJodHRwczovLzEzNS4yNTEuMTA4LjU1L2F1dGgvcmVhbG1zL3JhYmJpdG1xYXV0aCIsImF1ZCI6InJhYmJpdG1xLXJlc291cmNlIiwic3ViIjoiYTg5ODQzYWMtODI4Zi00YzRkLWE2NTYtNzA3ODA2NTZjYjJkIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoicmFiYml0bXEtcmVzb3VyY2UiLCJhdXRoX3RpbWUiOjAsInNlc3Npb25fc3RhdGUiOiJmZDA4NmMzNy0wNTY1LTRkNWUtYjFkZS1kMmQzNmUzZWQ2YjciLCJhY3IiOiIxIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwicmFiYml0bXF1c2VyIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJhdXRob3JpemF0aW9uIjp7InBlcm1pc3Npb25zIjpbeyJzY29wZXMiOlsicmFiYml0bXEtcmVzb3VyY2UucmVhZDoqLyoiXSwicnNpZCI6IjJjMzkwZmU0LTAyYWQtNDFjNy05OGEyLWNlYmI4YzYwY2NmMSIsInJzbmFtZSI6ImFsbHZob3N0In0seyJzY29wZXMiOlsicmFiYml0bXEtcmVzb3VyY2UtcmVhZCJdLCJyc2lkIjoiZTdmMTJlOTQtNGMzNC00M2Q4LWIyYjEtYzUxNmFmNjQ0Y2VlIiwicnNuYW1lIjoidmhvc3QxIn0seyJyc2lkIjoiMTJhYzNkMWMtMjhjMi00NTIxLThlMzMtMDk1MmVmZjEwYmQ5IiwicnNuYW1lIjoiRGVmYXVsdCBSZXNvdXJjZSJ9XX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6InRhbyB6b3UiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJ0YXpvdSIsImdpdmVuX25hbWUiOiJ0YW8iLCJmYW1pbHlfbmFtZSI6InpvdSIsImVtYWlsIjoidGFvLnpvdUBxcS5jb20ifQ.pMeRABUXHKNxA4qm7gKqnHU2qsnlHWqzJ8WhvuZjPu95yfxmTf_xYVhWKQdZQvbCMrfC62FeSxAhx-7CldhhHzeFulFFZiTGT4C_vtuJ-jvJd-dAtWFYzRxdjdeAdVXOBUcCd9fKJ1QYgsKqGUHllb6nn3ZC26HP80UfNFFEXw_MjKt_8fDvKugOjMya6QTQcRTVMMXwxYWvoygE3CeeDaMXZwBFiLQwz81WUHrUxVEPYm6Xmjmfft1LtwwIMYbO5ZjB0tL152dDWN-UFDBO9uOZJC30QAroQ6ApQjrDJihLtzUII0pBdZt7vFiOOkn7JEeFGvag4rU_1maXS3Vuug`

token expire date is Dec 13,2020.
Header:
{
  "alg": "RS256",
  "typ": "JWT",
  "kid": "gFfSF-hHN4HzVX5TPw3xd9Xzu6M7JmqmIKZg6QFolsM"
}
public-key:
-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyUiG/nOwpcL1PBio0djk
V2mqgowKcgmMcLVupLZn/Gzf1kpT1ftbA2wOArSuC/aIriRwBVdHK43+Pr6+FiKJ
NEusfo2E/gYimE4eHuaeL07wFT0USaOToL2R44L7Z6zXh2MWPtSrN2S20kiVErlp
6kJwwbtRKY2xc7KlMhM4JLNiaueCirWVzdJ0ZbuLBAFPPO4yzjXkb4eRBE7+eayU
HtYyA3DHu/T8VlaH5V40e/MCQEmb0kqs/v0veDwxGimWoEgJ9Bf019fVGk7p8fKd
geJFjRPRrZoN4YfJWsYY8kv+LGM73aKEFK+sXMTtrtUn9umH+1yGhaymthk6BUoH
+QIDAQAB
-----END PUBLIC KEY-----

Thanks for your response.

B.R,
Tao

**Comment by taijitao** [comment]
hi,
any update for this issue?
do you have any schedule?
B.R,
Tao

**Comment by michaelklishin** [comment]
We offer no ETA. Our priority right now is shipping 3.8. Keycloak support is a nice-to-have. This is open source software, though, so you are welcome to investigate and contribute.

**Comment by michaelklishin** [comment]
FTR, this PR was included into [3.8.0-rc.1](https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.8.0-rc.1).
