### ISSUE TITLE
Log info/warning when token key ID is not configured

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-auth-backend-uaa#44]
A token provides the key to use to check the signature with the `kid` field and this ID must match [a configured entry](https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2/blob/fc81a35773106ad28a7439107d9fe433e27bebeb/demo/rsa_keys/rabbitmq.config#L10).

If the key ID is not present in the configuration, there's no hint (error message, log message) that this is the cause of a failed authentication attempt. An info/warning log message message would help to diagnose the issue.

To reproduce, follow the steps of the demo (using asymmetrical keys) but [change the name of the default key in RabbitMQ configuration file](https://github.com/rabbitmq/rabbitmq-auth-backend-oauth2/blob/fc81a35773106ad28a7439107d9fe433e27bebeb/demo/rsa_keys/rabbitmq.config#L10) to something else. Make sure UAA issues token with a header like:

```json
{
  "alg": "RS256",
  "jku": "https://localhost:8080/uaa/token_keys",
  "kid": "legacy-token-key",
  "typ": "JWT"
}
```

and try to authenticate with an AMQP client. The authentication should fail, without much information about the missing key ID in the configuration.

**Comment by HoloRin** [comment]
For the sake of additional context, there are two way of specifying the jwt signing key the `uaa.yml`:
1. The old path, `jwt:token:signing-key`. If the key is specified in this form, it receives a key id of `legacy-token-key`, which must therefore match the `key_config` in the rabbitmq config.
2. The new path, `jwt:token:policy:keys:[phils-key]:signingKey`. In this form, the key id is `phils-key`, which must match the key ids given in the `key_config` in the rabbitmq config.
