### ISSUE TITLE
improve documentation to specify multi-level topic filtering when using MQTT

### ISSUE THREAD

**Issue by almarro1** [rabbitmq/rabbitmq-auth-backend-uaa#46]
Hi, I've been struggling for a time trying to use this plugin. It is quite powerful, but the documentation is poor. I give a couple of examples that should be improved:
1) Topic filtering patterns: it is not specified that multilevel filter can be used, separating levels with the ```.``` char. For example, if I want to restrict read to ```abc/cde/#```, then the regex pattern is ```abc.cde.*```
2) It is possible to use an additional claim in the token to look for the permissions. It should be configured in rabbit's ```advanced.config``` file.
```
[
  {rabbit, [
    {auth_backends, [rabbit_auth_backend_oauth2, rabbit_auth_backend_internal]}
  ]},
  {rabbitmq_auth_backend_oauth2, [
    {resource_server_id, <<"rabbitmq">>},
    {extra_scopes_source, <<"rabbit_extra_permissions">>},
 ...
]}
].
```

**Comment by michaelklishin** [comment]
1 is not specific to this plugin, it is how the MQTT plugin currently works (AMQP 0-9-1 and MQTT topic segment separators differ, so translation has to be done).

The extra scopes is actually fairly recent so all existing plugin docs predate it. We are not sure how useful it is as it was contributed by someone with very specific integration needs. You are welcome to contribute specific improvements. This is open source software after all.
