### ISSUE TITLE
No binaries available?

### ISSUE THREAD

**Issue by rishabhtulsian** [rabbitmq/rabbitmq-auth-backend-uaa#7]
I would like to use this plugin, are there any pre-build binaries available or instructions to build one?

**Comment by michaelklishin** [comment]
This plugin is experimental and can change drastically without a warning. I'd think twice before using it at this moment.

Here's a build against the tip of `3.6.x` (`stable`): [rabbitmq_auth_backend_uaa-0553ac3.ez.zip](https://github.com/rabbitmq/rabbitmq-auth-backend-uaa/files/1113449/rabbitmq_auth_backend_uaa-0553ac3.ez.zip).
